services:
  localstack:
    image: localstack/localstack:3.0
    container_name: tattoo-directory-localstack
    command:
      >- # This ensures LocalStack waits for init scripts to complete before starting services
      /usr/bin/tini -s -- /usr/local/bin/docker-entrypoint.sh
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566" # LocalStack gateway
      - "${LOCALSTACK_EXTERNAL_PORT_START:-4510}-${LOCALSTACK_EXTERNAL_PORT_END:-4559}:4510-4559" # External services port range
    environment:
      - SERVICES=dynamodb,opensearch,s3,apigateway,lambda,iam,secretsmanager
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localstack
      - PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack/data
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      # Resource optimization
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
      - SKIP_INFRA_DOWNLOADS=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/var/lib/localstack"
      - "../../localstack-init:/etc/localstack/init/ready.d"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1536M # Increased for better LocalStack performance
          cpus: "1.0" # Increased CPU allocation
        reservations:
          memory: 768M # Higher reservation for stability
          cpus: "0.5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=localstack"
    networks:
      - tattoo-directory-local

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.local
    container_name: tattoo-directory-backend
    ports:
      - "${BACKEND_PORT:-9000}:8080" # Lambda RIE port
      - "${BACKEND_DEBUG_PORT:-9229}:9229" # Node.js inspector port for debugging
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - DYNAMODB_TABLE_NAME=tattoo-directory-local
      - OPENSEARCH_ENDPOINT=http://localstack:4566
      - NODE_ENV=development
      - LAMBDA_TASK_ROOT=/var/task
      - ENABLE_DEBUG=${ENABLE_BACKEND_DEBUG:-false}
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - ../../backend/src:/var/task/src:ro
      - ../../backend/package.json:/var/task/package.json:ro
      - ../../backend/package-lock.json:/var/task/package-lock.json:ro
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/2015-03-31/functions/function/invocations",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=backend"
    networks:
      - tattoo-directory-local

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.local
    container_name: tattoo-directory-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
      - "${FRONTEND_DEBUG_PORT:-9230}:9230" # Next.js debug port
    environment:
      - NEXT_PUBLIC_ENVIRONMENT=local
      - NEXT_PUBLIC_API_URL=http://backend:8080/2015-03-31/functions/function/invocations
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyA7T0Q2gkVZlg9_da2085l8FO2RLKx5ySo
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - ENABLE_DEBUG=${ENABLE_FRONTEND_DEBUG:-false}
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ../../frontend/src:/app/src:ro
      - ../../frontend/public:/app/public:ro
      - ../../frontend/package.json:/app/package.json:ro
      - ../../frontend/package-lock.json:/app/package-lock.json:ro
      - ../../frontend/next.config.mjs:/app/next.config.mjs:ro
      - ../../frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ../../frontend/postcss.config.mjs:/app/postcss.config.mjs:ro
      - ../../frontend/jsconfig.json:/app/jsconfig.json:ro
      - ../../frontend/.eslintrc.json:/app/.eslintrc.json:ro
      # Exclude node_modules and .next from volume mounts for performance
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "node", "/app/health-check.js"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=frontend"
    networks:
      - tattoo-directory-local

  swagger-ui:
    image: nginx:alpine
    container_name: tattoo-directory-swagger
    ports:
      - "${SWAGGER_PORT:-8080}:80"
    volumes:
      - ../../backend/docs/openapi.yaml:/usr/share/nginx/html/openapi/openapi.yaml:ro
      - ../../backend/docs/swagger-ui.html:/usr/share/nginx/html/index.html:ro
      - ../../backend/docs/swagger-config.js:/usr/share/nginx/html/swagger-config.js:ro
    depends_on:
      backend:
        condition: service_started
    healthcheck:
      test:
        ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.1"
        reservations:
          memory: 32M
          cpus: "0.05"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        labels: "service=swagger-ui"
    networks:
      - tattoo-directory-local

  data-seeder:
    build:
      context: ../../scripts
      dockerfile: data-seeder/Dockerfile.seeder
    container_name: tattoo-directory-seeder
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - DYNAMODB_TABLE_NAME=tattoo-directory-local
      - OPENSEARCH_ENDPOINT=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - ../../scripts/test-data:/app/test-data:ro
    profiles:
      - seeding
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
        reservations:
          memory: 128M
          cpus: "0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        labels: "service=data-seeder"
    networks:
      - tattoo-directory-local

networks:
  tattoo-directory-local:
    driver: bridge

volumes:
  localstack-data:
    driver: local
