# Docker Compose Override for macOS
# Use this file on macOS systems for optimal performance and compatibility
# Usage: docker-compose -f dev-tools/docker/docker-compose.local.yml -f dev-tools/docker/docker-compose.macos.yml up

version: '3.8'

services:
  localstack:
    # macOS-specific Docker socket and volume handling
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack
      - ./localstack-init:/etc/localstack/init/ready.d:ro
    environment:
      # macOS-specific LocalStack configuration
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TMPDIR=/tmp

  backend:
    # macOS optimized volume mounts with delegated consistency
    volumes:
      - ./backend/src:/var/task/src:ro,delegated
      - ./backend/package.json:/var/task/package.json:ro
      - ./backend/package-lock.json:/var/task/package-lock.json:ro
    environment:
      # macOS-specific environment variables
      - LAMBDA_TASK_ROOT=/var/task

  frontend:
    # macOS-specific file watching and volume configuration
    volumes:
      - ./frontend/src:/app/src:ro,delegated
      - ./frontend/public:/app/public:ro,delegated
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:ro
      - ./frontend/next.config.mjs:/app/next.config.mjs:ro
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs:ro
      - ./frontend/jsconfig.json:/app/jsconfig.json:ro
      - ./frontend/.eslintrc.json:/app/.eslintrc.json:ro
      # Performance volumes for macOS
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    environment:
      # macOS-specific file watching (native fsevents work well)
      - WATCHPACK_POLLING=false
      - CHOKIDAR_USEPOLLING=false
      - NEXT_TELEMETRY_DISABLED=1

  swagger-ui:
    volumes:
      - ./backend/docs/openapi.yaml:/usr/share/nginx/html/openapi/openapi.yaml:ro
      - ./backend/docs/swagger-ui.html:/usr/share/nginx/html/index.html:ro
      - ./backend/docs/swagger-config.js:/usr/share/nginx/html/swagger-config.js:ro

  data-seeder:
    volumes:
      - ./scripts/test-data:/app/test-data:ro,delegated

# macOS-specific volumes for better performance
volumes:
  frontend_node_modules:
    driver: local
  frontend_next:
    driver: local