# Docker Compose Override for Linux
# Use this file on Linux systems for optimal performance and compatibility
# Usage: docker-compose -f dev-tools/docker/docker-compose.local.yml -f dev-tools/docker/docker-compose.linux.yml up

version: '3.8'

services:
  localstack:
    # Linux-specific Docker socket handling
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack
      - ./localstack-init:/etc/localstack/init/ready.d:ro
    environment:
      # Linux-specific LocalStack configuration
      - DOCKER_HOST=unix:///var/run/docker.sock
    # Linux typically has faster startup times
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    # Linux optimized volume mounts
    volumes:
      - ./backend/src:/var/task/src:ro
      - ./backend/package.json:/var/task/package.json:ro
      - ./backend/package-lock.json:/var/task/package-lock.json:ro
    environment:
      # Linux-specific environment variables
      - LAMBDA_TASK_ROOT=/var/task

  frontend:
    # Linux-specific file watching and volume configuration
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:ro
      - ./frontend/next.config.mjs:/app/next.config.mjs:ro
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs:ro
      - ./frontend/jsconfig.json:/app/jsconfig.json:ro
      - ./frontend/.eslintrc.json:/app/.eslintrc.json:ro
      # Anonymous volumes for performance
      - /app/node_modules
      - /app/.next
    environment:
      # Linux-specific file watching (inotify works well)
      - WATCHPACK_POLLING=false
      - CHOKIDAR_USEPOLLING=false
      - NEXT_TELEMETRY_DISABLED=1

  swagger-ui:
    volumes:
      - ./backend/docs/openapi.yaml:/usr/share/nginx/html/openapi/openapi.yaml:ro
      - ./backend/docs/swagger-ui.html:/usr/share/nginx/html/index.html:ro
      - ./backend/docs/swagger-config.js:/usr/share/nginx/html/swagger-config.js:ro

  data-seeder:
    volumes:
      - ./scripts/test-data:/app/test-data:ro