# Docker Compose Override for Windows
# Use this file on Windows systems for optimal performance and compatibility
# Usage: docker-compose -f dev-tools/docker/docker-compose.local.yml -f dev-tools/docker/docker-compose.windows.yml up

services:
  localstack:
    # Windows-specific Docker socket handling
    volumes:
      # Use named pipe for Windows Docker Desktop
      - //var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack
      - ../../localstack-init:/etc/localstack/init/ready.d:ro
    environment:
      # Windows-specific LocalStack configuration
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_VOLUME_DIR=${PWD}/localstack-data
    # Increased timeouts for Windows
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 45s

  backend:
    # Windows path handling and performance optimization
    volumes:
      - ../../backend/src:/var/task/src:ro,cached
      - ../../backend/package.json:/var/task/package.json:ro
      - ../../backend/package-lock.json:/var/task/package-lock.json:ro
    environment:
      # Windows-specific environment variables
      - LAMBDA_TASK_ROOT=/var/task
      - AWS_LAMBDA_RUNTIME_API_TIMEOUT=30000
    # Extended startup time for Windows
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/2015-03-31/functions/function/invocations"]
      interval: 45s
      timeout: 15s
      retries: 3
      start_period: 90s

  frontend:
    # Windows-specific file watching and volume configuration
    volumes:
      - ../../frontend/src:/app/src:ro,cached
      - ../../frontend/public:/app/public:ro,cached
      - ../../frontend/package.json:/app/package.json:ro
      - ../../frontend/package-lock.json:/app/package-lock.json:ro
      - ../../frontend/next.config.mjs:/app/next.config.mjs:ro
      - ../../frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ../../frontend/postcss.config.mjs:/app/postcss.config.mjs:ro
      - ../../frontend/jsconfig.json:/app/jsconfig.json:ro
      - ../../frontend/.eslintrc.json:/app/.eslintrc.json:ro
      # Performance volumes for Windows
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    environment:
      # Windows-specific file watching configuration
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=2000
      - NEXT_TELEMETRY_DISABLED=1
      # Windows path handling
      - FORCE_COLOR=1
    # Extended startup time for Windows
    healthcheck:
      test: ["CMD", "node", "/app/health-check.js"]
      interval: 45s
      timeout: 15s
      retries: 3
      start_period: 90s

  swagger-ui:
    volumes:
      - ../../backend/docs/openapi.yaml:/usr/share/nginx/html/openapi/openapi.yaml:ro
      - ../../backend/docs/swagger-ui.html:/usr/share/nginx/html/index.html:ro
      - ../../backend/docs/swagger-config.js:/usr/share/nginx/html/swagger-config.js:ro

  data-seeder:
    volumes:
      - ../../scripts/test-data:/app/test-data:ro,cached

# Windows-specific volumes for better performance
volumes:
  frontend_node_modules:
    driver: local
  frontend_next:
    driver: local