    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - DYNAMODB_TABLE_NAME=tattoo-directory-local
      - OPENSEARCH_ENDPOINT=http://localstack:4566
      - OPENSEARCH_INDEX=tattoo-artists
      - NODE_ENV=development
      - LAMBDA_TASK_ROOT=/var/task
      - ENABLE_DEBUG=${ENABLE_BACKEND_DEBUG:-false}      - OPENSEARCH_ENDPOINT=http://localstack:4566
      - OPENSEARCH_INDEX=tattoo-artists
      - NODE_ENV=development  data-seeder:
    build:
      context: ../../scripts
      dockerfile: data-seeder/Dockerfile.seeder
    container_name: tattoo-directory-seeder
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - DYNAMODB_TABLE_NAME=tattoo-directory-local
      - OPENSEARCH_ENDPOINT=http://localstack:4566
      - OPENSEARCH_INDEX=artists-local  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.local
    container_name: tattoo-directory-backend
    ports:
      - "${BACKEND_PORT:-9000}:8080" # Lambda RIE port
      - "${BACKEND_DEBUG_PORT:-9229}:9229" # Node.js inspector port for debugging
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "1.0"
        reservations:
          memory: "256M"
          cpus: "0.25"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",