services:
  localstack:
    image: localstack/localstack:3.0
    container_name: tattoo-directory-localstack
    command:
      >- # This ensures LocalStack waits for init scripts to complete before starting services
      /usr/bin/tini -s -- /usr/local/bin/docker-entrypoint.sh
    ports:
      - "127.0.0.1:${LOCALSTACK_PORT:-4566}:4566" # LocalStack gateway - bind to localhost only
      - "127.0.0.1:${LOCALSTACK_EXTERNAL_PORT_START:-4510}-${LOCALSTACK_EXTERNAL_PORT_END:-4559}:4510-4559" # External services port range
    environment:
      - SERVICES=dynamodb,opensearch,s3,apigateway,lambda,iam,secretsmanager
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localstack
      - PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack/data
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      # Resource optimization
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
      - SKIP_INFRA_DOWNLOADS=1
      # Security settings
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
      - ENFORCE_IAM=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "localstack-data:/var/lib/localstack"
      - "../../localstack-init:/etc/localstack/init/ready.d:ro"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1536M # Increased for better LocalStack performance
          cpus: "1.0" # Increased CPU allocation
        reservations:
          memory: 768M # Higher reservation for stability
          cpus: "0.5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=localstack,security.level=medium"
    security_opt:
      - no-new-privileges:true
    read_only: false # LocalStack needs write access
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    labels:
      - "com.tattoo-directory.service=localstack"
      - "com.tattoo-directory.security.level=medium"
      - "com.tattoo-directory.access.internal=true"
      - "com.tattoo-directory.access.external=false"
    networks:
      tattoo-directory-local:
        ipv4_address: 172.20.0.10

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.local
    container_name: tattoo-directory-backend
    ports:
      - "127.0.0.1:${BACKEND_PORT:-9000}:8080" # Lambda RIE port - bind to localhost only
      - "127.0.0.1:${BACKEND_DEBUG_PORT:-9229}:9229" # Node.js inspector port for debugging
    environment:
      - AWS_ENDPOINT_URL=http://172.20.0.10:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - DYNAMODB_TABLE_NAME=tattoo-directory-local
      - OPENSEARCH_ENDPOINT=http://172.20.0.10:4566
      - NODE_ENV=development
      - LAMBDA_TASK_ROOT=/var/task
      - ENABLE_DEBUG=${ENABLE_BACKEND_DEBUG:-false}
      # Security environment variables
      - SECURITY_VALIDATION_ENABLED=true
      - CORS_ORIGIN=http://localhost:3000
      - RATE_LIMIT_ENABLED=true
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - ../../backend/src:/var/task/src:ro
      - ../../backend/package.json:/var/task/package.json:ro
      - ../../backend/package-lock.json:/var/task/package-lock.json:ro
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/2015-03-31/functions/function/invocations",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=backend,security.level=high"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/task/.npm:noexec,nosuid,size=50m
    user: "1000:1000"
    labels:
      - "com.tattoo-directory.service=backend"
      - "com.tattoo-directory.security.level=high"
      - "com.tattoo-directory.access.internal=true"
      - "com.tattoo-directory.access.external=true"
    networks:
      tattoo-directory-local:
        ipv4_address: 172.20.0.20

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.local
    container_name: tattoo-directory-frontend
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-3000}:3000"
      - "127.0.0.1:${FRONTEND_DEBUG_PORT:-9230}:9230" # Next.js debug port
    env_file:
      - ../.env.local
    environment:
      - NEXT_PUBLIC_ENVIRONMENT=local
      - NEXT_PUBLIC_API_URL=http://backend:8080/2015-03-31/functions/function/invocations
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - ENABLE_DEBUG=${ENABLE_FRONTEND_DEBUG:-false}
      # Security environment variables
      - SECURITY_HEADERS_ENABLED=true
      - CSP_ENABLED=true
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ../../frontend/src:/app/src:ro
      - ../../frontend/public:/app/public:ro
      - ../../frontend/package.json:/app/package.json:ro
      - ../../frontend/package-lock.json:/app/package-lock.json:ro
      - ../../frontend/next.config.mjs:/app/next.config.mjs:ro
      - ../../frontend/tailwind.config.js:/app/tailwind.config.js:ro
      - ../../frontend/postcss.config.mjs:/app/postcss.config.mjs:ro
      - ../../frontend/jsconfig.json:/app/jsconfig.json:ro
      - ../../frontend/.eslintrc.json:/app/.eslintrc.json:ro
      # Exclude node_modules and .next from volume mounts for performance
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "node", "/app/health-check.js"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=frontend,security.level=high"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/.next:noexec,nosuid,size=200m
    user: "1000:1000"
    labels:
      - "com.tattoo-directory.service=frontend"
      - "com.tattoo-directory.security.level=high"
      - "com.tattoo-directory.access.internal=true"
      - "com.tattoo-directory.access.external=true"
    networks:
      tattoo-directory-local:
        ipv4_address: 172.20.0.30

  swagger-ui:
    image: nginx:alpine
    container_name: tattoo-directory-swagger
    ports:
      - "127.0.0.1:${SWAGGER_PORT:-8080}:80"
    volumes:
      - ../../backend/docs/openapi.yaml:/usr/share/nginx/html/openapi/openapi.yaml:ro
      - ../../backend/docs/swagger-ui.html:/usr/share/nginx/html/index.html:ro
      - ../../backend/docs/swagger-config.js:/usr/share/nginx/html/swagger-config.js:ro
    depends_on:
      backend:
        condition: service_started
    healthcheck:
      test:
        ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.1"
        reservations:
          memory: 32M
          cpus: "0.05"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        labels: "service=swagger-ui,security.level=low"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
      - /var/cache/nginx:noexec,nosuid,size=10m
      - /var/run:noexec,nosuid,size=10m
    user: "101:101"
    labels:
      - "com.tattoo-directory.service=swagger-ui"
      - "com.tattoo-directory.security.level=low"
      - "com.tattoo-directory.access.internal=false"
      - "com.tattoo-directory.access.external=true"
    networks:
      tattoo-directory-local:
        ipv4_address: 172.20.0.40

  data-seeder:
    build:
      context: ../../scripts
      dockerfile: data-seeder/Dockerfile.seeder
    container_name: tattoo-directory-seeder
    environment:
      - AWS_ENDPOINT_URL=http://172.20.0.10:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - DYNAMODB_TABLE_NAME=tattoo-directory-local
      - OPENSEARCH_ENDPOINT=http://172.20.0.10:4566
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - ../../scripts/test-data:/app/test-data:ro
    profiles:
      - seeding
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
        reservations:
          memory: 128M
          cpus: "0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        labels: "service=data-seeder,security.level=medium"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    user: "1000:1000"
    labels:
      - "com.tattoo-directory.service=data-seeder"
      - "com.tattoo-directory.security.level=medium"
      - "com.tattoo-directory.access.internal=true"
      - "com.tattoo-directory.access.external=false"
    networks:
      tattoo-directory-local:
        ipv4_address: 172.20.0.50

networks:
  tattoo-directory-local:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: tattoo-local-br0
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    labels:
      - "com.tattoo-directory.network=local"
      - "com.tattoo-directory.environment=development"

volumes:
  localstack-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/localstack-data